### ISSUE TITLE
Places - Finish lines, finish migration

### ISSUE THREAD

**Issue by skyksandr** [skyderby/skyderby#136]
## Minimal dataset

**Country**: Norway

**Place**: Hoven (Lat 61.88504129, Lon: 6.83213621)

**Finish line**
Exit 

Latitude 61.88504129
Longitude 6.83213621

Coordinates

Start latitude 61.8741087555
Start longitude 6.8353044243

End latitude 61.8751681482
End longitude 6.8425881017

## How it looks in Tournaments now

![Снимок экрана 2019-05-02 в 10 23 02](https://user-images.githubusercontent.com/5262979/57061097-64ad9c80-6cc4-11e9-9f40-62df89faa700.png)

## Initial description

At some point, we needed to use finish lines not only in Tournaments but also in Online competitions.

So I made a first step to abstract finish lines and created a model and simple views for it.

What we need now is to complete migration and make a good views.

## Implementation plan

- [ ] Implement map with centerline and finish line in FinishLine form view
- [ ] Show map in the show view
- [ ] Show elements as cards with map in the index view
- [ ] Add finish line to tournaments
- [ ] Migrate data on production
- [ ] Add ability to view finish line from tournament#show (maybe in modal?)
- [ ] Drop `start_lat, start_lon, ...` fields
- [ ] Add ability to view finish line from online_competitions#show
